### PR TITLE
feat: update to feathers 5

### LINKED ISSUE #48: Next version for feathers 5
We are currently trying to use your plugin with feathers version 5.  To get it to work some dependencies like the `feathers-utils` & `feathers-hooks-common` libs have to be updated as well. I saw that you already planned that somehow for `feathers-utils`: https://github.com/fratzinger/feathers-utils/issues/4. As it seems that for example "only" `getItems` & `replaceItems` is used from `feathers-hooks-common` do you think it would be possible to add a light version / just the needed code of that functionality to `feathers-casl` directly, so dependencies would be reduced? 
Would like to do / help you with that update.

### PR DESCRIPTION
**Pull request by lukashass**
Closes #48 

This updates
- `feathers` to version 5,
- `feathers-hooks-common` to an updated version submitted here: https://github.com/feathersjs-ecosystem/feathers-hooks-common/pull/623
- `feathers-utils` to https://github.com/fratzinger/feathers-utils/pull/10

### CODE REVIEW

**Comment by fratzinger** [comment]
Thanks for both PRs!

How is this backwards compatible to feathers@4?

**Comment by lukashass** [comment]
I'm unsure about backwards compatibility right now. I see a few problems:

- import of `feathers` is no longer `default` (only used in test files though)
- types of e.g. `Application` have changed quite significantly

It might be possible to circumvent those by moving `@feathersjs/*` dependencies to `peerDependencies`. That might be a breaking change on its own though. :thinking:

**Comment by fratzinger** [comment]
Please see https://github.com/fratzinger/feathers-casl/tree/dove

**Comment by fratzinger** [comment]
Hey folks @lukashass, @dasantonym:

I continued my work in the dove branch: https://github.com/fratzinger/feathers-casl/tree/dove
And finally released a pre version as `feathers-casl@pre`. It got a few new things:
- feathers dove support for `@feathersjs/memory`, `@feathersjs/knex`, `@feathersjs/mongodb`, `feathers-sequelize@pre`
- ‼️ no support for `feathers-memory`, `feathers-knex`, `feathers-objection`, `feathers-mongodb`, `feathers-mongoose` because they aren't compatible with dove (yet) (or at least I don't know of a support)
- cjs & esm support by https://github.com/unjs/unbuild
- peerDependency `@casl/ability`: To follow best practices `feathers-casl` no longer exports stuff from `@casl/ability`, so you have to install it on your own and define the `ability` with it. A few tests are failing with the newest major release of `@casl/ability` (v6), so currently only `@casl/ability@5` is supported. But `@casl/ability@5` was used in `feathers-casl` before. I'll work on that in a future pre release.
- around hook: the hook `authorize` can also be used as an `around` hook now. I've added tests for `@feathersjs/memory` to make sure it works correctly.
- tests with vitest
- many more small things have changed

Things I have to do in future pre releases:
- support for `@casl/ability@6`
- add `around` hook for `checkBasicPermission`
- update the docs. A few things have to be updated. Especially the supported adapters. I haven't touched the docs yet.
- maybe add support for `feathers-objection`, `feathers-mongoose` if they got support for dove

Thanks again for the work, you have put into this! I close this PR, because I think I got all covered in the dove branch now. Please let me know, what you think. I'm happy to work on recommendations from you based on the current version of the dove branch. (see #79)

**Pull request closed without merging**
