### PR TITLE
highlight changes required for dove

### PR DESCRIPTION
**Pull request by marshallswain**
- latest deps
- most types are set to `any` to highlight where we need type changes.
- Adds a test set for @feathersjs/mongodb
- Allows filters to be passed into mergeQuery

There are still 3 or 4 broken tests in this PR.

### CODE REVIEW

**Comment by marshallswain** [comment]
image

@fratzinger, why should the first `.find` in the above screenshot fail with the given message?  I don't see where the message is even specified.  It seems like that query should work and return an empty array result.  Please enlighten me.

**Comment by marshallswain** [comment]
I was able to make the `authorize` hook work as an around, before, after hook.

Screen Shot 2022-08-28 at 5 12 07 PM
.

**Comment by marshallswain** [comment]
I've used all of the time I have available to work on this PR, so feel free to grab what you want and close.

**Comment by fratzinger** [comment]
Hey marshall, thanks for the PR! This marks a milestone for me, because it's the first time you've contributed to one of my repos and not the other way around 😅🎉

Thanks to your work, I continued my work in the dove branch: https://github.com/fratzinger/feathers-casl/tree/dove
And finally released a pre version as `feathers-casl@pre`. It got a few new things:
- feathers dove support for `@feathersjs/memory`, `@feathersjs/knex`, `@feathersjs/mongodb`, `feathers-sequelize@pre`
- ‼️ no support for `feathers-memory`, `feathers-knex`, `feathers-objection`, `feathers-mongodb`, `feathers-mongoose` because they aren't compatible with dove (yet) (or at least I don't know of a support)
- cjs & esm support by https://github.com/unjs/unbuild
- peerDependency `@casl/ability`: To follow best practices `feathers-casl` no longer exports stuff from `@casl/ability`, so you have to install it on your own and define the `ability` with it. A few tests are failing with the newest major release of `@casl/ability` (v6), so currently only `@casl/ability@5` is supported. But `@casl/ability@5` was used in `feathers-casl` before. I'll work on that in a future pre release.
- around hook: the hook `authorize` can also be used as an `around` hook now. I've added tests for `@feathersjs/memory` to make sure it works correctly.
- tests with vitest
- many more small things have changed

Things I have to do in future pre releases:
- support for `@casl/ability@6`
- add `around` hook for `checkBasicPermission`
- update the docs. A few things have to be updated. Especially the supported adapters. I haven't touched the docs yet.
- maybe add support for `feathers-objection`, `feathers-mongoose` if they got support for dove

Thanks again for the work, you have put into this! I close this PR, because I think I got all covered in the dove branch now.

**Pull request closed without merging**
